KERNEL_SRC := $(HOME)/repo/raspberrypi/linux
ARCH := arm
CROSS_COMPILE := $(HOME)/repo/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
BUILD_DIR = `pwd`

MODULES := rtled.o rtswitch.o

obj-m := $(MODULES)

all: $(MODULES:.o=.ko)

rtled.ko: rtled.c
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERNEL_SRC) M=$(BUILD_DIR) V=1 modules

rtswitch.ko: rtswitch.c
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERNEL_SRC) M=$(BUILD_DIR) V=1 modules

clean:
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERNEL_SRC) M=$(BUILD_DIR) V=1 clean

install: rtled.ko rtswitch.ko uninstall
	insmod rtled.ko
	insmod rtswitch.ko
	[ -e /dev/rtswitch2 ] || sleep 1
	chmod 666 /dev/rt*

uninstall:
	[ ! -e /dev/rtled0 ] || rmmod rtled.ko
	[ ! -e /dev/rtswitch0 ] || rmmod rtswitch.ko

